#!/bin/bash
# Script used to create snapshots of all existing subvolumes.
#
# ## How to use:
#
# subvol-snapshot-all [HINT]
#

HINT=${1}

find /subvol/subvolumes/* -maxdepth 0 -type d | xargs -n 1 basename | xargs -n 1 -I :SUBVOLUME subvol snapshot create :SUBVOLUME "${HINT}"

